name: Build macOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build application
        run: |
          pyinstaller \
            --windowed \
            --name "Untuk-Caca" \
            --add-data "fonts:fonts" \
            --add-data "models:models" \
            main.py

      - name: Create final package
        run: |
          mkdir package

          cp -R "dist/Untuk-Caca.app" package/
          cp "BUKA_AKU.txt" package/

          cd package

          zip -r "../Untuk-Caca-Package.zip" .

      - name: Upload final package
        uses: actions/upload-artifact@v4
        with:
          name: Untuk-Caca-Package
          path: Untuk-Caca-Package.zip
